//======================================//
//======================================//
//======================================//
//======================================//

//Documento de datos para la generacion de registro

// // Rangos de edades para cada nivel
// export const EDAD_RANGOS = {
//   Inicial: { min: 4, max: 6 },
//   Primario: { min: 6, max: 12 },
//   Secundario: { min: 12, max: 18 },
//   Terciario: { min: 18, max: 45 },
// };

// // Niveles educativos y sus códigos
// export const NIVELES_EDUCATIVOS = [
//   { codigo: 101, nombre: "Inicial" },
//   { codigo: 102, nombre: "Primaria" },
//   { codigo: 110, nombre: "Secundaria" },
//   { codigo: 115, nombre: "Superior" },
// ];

const nombresFemeninosOriginales = [
  "Sofía",
  "Valentina",
  "Martina",
  "Camila",
  "Victoria",
  "Lucía",
  "Florencia",
  "Milagros",
  "Rocío",
  "Sol",
  "Juliana",
  "Julieta",
  "Melanie",
  "Natalia",
  "Fátima",
  "María",
  "Emilia",
  "Silvana",
  "Malena",
  "Aymará",
];

const nombresMasculinosOriginales = [
  "Lucas",
  "Daniel",
  "Sergio",
  "Fabian",
  "Mario",
  "Leonardo",
  "Leandro",
  "Diego",
  "Hector",
  "Carlos",
  "Axel",
  "Dante",
  "Mateo",
  "Agustín",
  "Santiago",
  "Nicolás",
  "Joaquín",
  "Facundo",
  "Matías",
  "Leonardo",
  "Tomás",
  "Emiliano",
  "Fausto",
  "Mauricio",
  "Ruperto",
];

// Relaciones nombre genero
export const DataNombresFemeninos = nombresFemeninosOriginales.map(
  (nombre) => ({
    name: nombre,
    gender: "Femenino",
  })
);
export const DataNombresMasculinos = nombresMasculinosOriginales.map(
  (nombre) => ({
    name: nombre,
    gender: "Masculino",
  })
);

//Array de apellidos
export const DataApellidos = [
  "Mernes",
  "García",
  "Martínez",
  "Rodríguez",
  "López",
  "Fernández",
  "González",
  "Pérez",
  "Ramírez",
  "Sánchez",
  "Romero",
  "Torres",
  "Díaz",
  "Alvarez",
  "Ruiz",
  "Hernández",
  "Mendoza",
  "Flores",
  "Gómez",
  "Ortega",
  "Silva",
  "Majda",
  "Piazza",
  "Britez",
  "Fárias",
  "Valdez",
  "Rios",
  "Meyer",
  "Caeiro",
  "Wanwewi",
];

//=================================//
//por que tuve q hacer esto, rellenar luego
export const DataMaterias = {
  Primario: [
    {
      año: "1er Año",
      id: 1,
      materias: [
        { id: 1, name: "Matemáticas" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Ciencias Sociales" },
        { id: 4, name: "Ciencias Naturales" },
        { id: 5, name: "Inglés" },
        { id: 6, name: "Plástica y Artística" },
        { id: 7, name: "Educación Física" },
        { id: 8, name: "Geografía" },
      ],
    },
    {
      año: "2do Año",
      id: 2,
      materias: [
        { id: 1, name: "Matemáticas" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Ciencias Sociales" },
        { id: 4, name: "Ciencias Naturales" },
        { id: 5, name: "Inglés" },
        { id: 6, name: "Plástica y Artística" },
        { id: 7, name: "Educación Física" },
        { id: 8, name: "Geografía" },
      ],
    },
    {
      año: "3er Año",
      id: 3,
      materias: [
        { id: 1, name: "Matemáticas" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Ciencias Sociales" },
        { id: 4, name: "Ciencias Naturales" },
        { id: 5, name: "Inglés" },
        { id: 6, name: "Plástica y Artística" },
        { id: 7, name: "Educación Física" },
        { id: 8, name: "Geografía" },
      ],
    },
    {
      año: "4to Año",
      id: 4,
      materias: [
        { id: 1, name: "Matemáticas" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Ciencias Sociales" },
        { id: 4, name: "Ciencias Naturales" },
        { id: 5, name: "Inglés" },
        { id: 6, name: "Plástica y Artística" },
        { id: 7, name: "Educación Física" },
        { id: 8, name: "Geografía" },
      ],
    },
    {
      año: "5to Año",
      id: 5,
      materias: [
        { id: 1, name: "Matemáticas" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Ciencias Sociales" },
        { id: 4, name: "Ciencias Naturales" },
        { id: 5, name: "Inglés" },
        { id: 6, name: "Plástica y Artística" },
        { id: 7, name: "Educación Física" },
        { id: 8, name: "Geografía" },
      ],
    },
    {
      año: "6to Año",
      id: 6,
      materias: [
        { id: 1, name: "Matemáticas" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Ciencias Sociales" },
        { id: 4, name: "Ciencias Naturales" },
        { id: 5, name: "Inglés" },
        { id: 6, name: "Plástica y Artística" },
        { id: 7, name: "Educación Física" },
        { id: 8, name: "Geografía" },
      ],
    },
  ],
  Secundario: [
    {
      año: "1º Año",
      id: 1,
      materias: [
        { id: 1, name: "Matemática" },
        { id: 2, name: "Biología" },
        { id: 3, name: "Lengua y Literatura" },
        { id: 4, name: "Geografía" },
        { id: 5, name: "Historia" },
        { id: 6, name: "Educación Tecnológica" },
        { id: 7, name: "Educación Ciudadana" },
        { id: 8, name: "Inglés 1°3 y 4" },
        { id: 9, name: "Artes Música o Artes Visuales" },
        { id: 10, name: "Educación Física" },
      ],
    },
    {
      año: "2º Año",
      id: 2,
      materias: [
        { id: 1, name: "Matemática" },
        { id: 2, name: "Biología" },
        { id: 3, name: "Lengua y Literatura" },
        { id: 4, name: "Geografía" },
        { id: 5, name: "Historia" },
        { id: 6, name: "Educación Tecnológica" },
        { id: 7, name: "Educación Ciudadana" },
        { id: 8, name: "Idioma Inglés" },
        { id: 9, name: "Inglés 2°8°" },
        { id: 10, name: "Artes Música o Artes Visuales" },
        { id: 11, name: "Educación Física" },
      ],
    },
    {
      año: "3º Año",
      id: 3,
      materias: [
        { id: 1, name: "Matemática" },
        { id: 2, name: "Biología" },
        { id: 3, name: "Lengua y Literatura" },
        { id: 4, name: "Geografía" },
        { id: 5, name: "Historia" },
        { id: 6, name: "Educación Tecnológica" },
        { id: 7, name: "Educación Ciudadana" },
        { id: 8, name: "Inglés/Francés" },
        { id: 9, name: "Ingl3°7 y 6" },
        { id: 10, name: "Artes Música o Artes Visuales" },
        { id: 11, name: "Educación Física" },
      ],
    },
    {
      año: "4º Año",
      id: 4,
      materias: [
        { id: 1, name: "Matemática" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Inglés/Francés" },
        { id: 4, name: "Educación Física" },
        { id: 5, name: "Biología" },
        { id: 6, name: "Historia" },
        { id: 7, name: "Geografía" },
        { id: 8, name: "Formación Ética y Ciudadana" },
        { id: 9, name: "Tecnologías de la Información" },
        { id: 10, name: "Economía" },
        { id: 11, name: "Físico-Química" },
        { id: 12, name: "EDI" },
        { id: 13, name: "Laboratorio" },
        {
          id: 14,
          name: "Taller de Producción en Lenguajes: Literatura y otras Artes",
        },
        { id: 15, name: "Historia de la Vida y de la Tierra" },
      ],
    },
    {
      id: 5,
      año: "5º Año",
      materias: [
        { id: 1, name: "Matemática" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Inglés/Francés" },
        { id: 4, name: "Educación Física" },
        { id: 5, name: "Biología" },
        { id: 6, name: "Historia" },
        { id: 7, name: "Geografía" },
        { id: 8, name: "Formación Ética y Ciudadana" },
        { id: 9, name: "Tecnologías de la Información" },
        { id: 10, name: "Economía" },
        { id: 11, name: "Físico-Química" },
        { id: 12, name: "EDI" },
        { id: 13, name: "Materias específicas del bachillerato" },
      ],
    },
    {
      id: 6,
      año: "6º Año",
      materias: [
        { id: 1, name: "Matemática" },
        { id: 2, name: "Lengua y Literatura" },
        { id: 3, name: "Inglés/Francés" },
        { id: 4, name: "Educación Física" },
        { id: 5, name: "Biología" },
        { id: 6, name: "Historia" },
        { id: 7, name: "Geografía" },
        { id: 8, name: "Formación Ética y Ciudadana" },
        { id: 9, name: "Tecnologías de la Información" },
        { id: 10, name: "Economía" },
        { id: 11, name: "Físico-Química" },
        { id: 12, name: "EDI" },
        { id: 13, name: "Materias específicas del bachillerato" },
      ],
    },
  ],
  Terciario: [
    {
      año: "1er Año",
      id: 1,
      materias: [
        { id: 1, name: "TALLER DE LENGUAJE DE PROGRAMACION" },
        { id: 2, name: "ARQUITECTURA Y SISTEMAS OPERATIVOS" },
        { id: 3, name: "ALGORITMOS Y ESTRUCTURAS DE DATOS" },
        { id: 4, name: "BASE DE DATOS I" },
        { id: 5, name: "TALLER DE INTEGRACION I" },
        { id: 6, name: "MATEMATICA APLICADA I" },
        { id: 7, name: "INGLES I" },
        { id: 8, name: "MATEMATICA APLICADA II" },
        { id: 9, name: "INGLES II" },
        { id: 10, name: "BASE DE DATOS II" },
        { id: 11, name: "INGENIERIA DE SOFTWARE" },
        { id: 12, name: "TALLER DE INTEGRACION II" },
        { id: 13, name: "ORIENTACION Y VALORES" },
        { id: 14, name: "MINERIA DE DATOS" },
      ],
    },
    {
      año: "2do Año",
      id: 2,
      materias: [
        { id: 1, name: "TALLER DE LENGUAJE DE PROGRAMACION" },
        { id: 2, name: "ARQUITECTURA Y SISTEMAS OPERATIVOS" },
        { id: 3, name: "ALGORITMOS Y ESTRUCTURAS DE DATOS" },
        { id: 4, name: "BASE DE DATOS I" },
        { id: 5, name: "TALLER DE INTEGRACION I" },
        { id: 6, name: "MATEMATICA APLICADA I" },
        { id: 7, name: "INGLES I" },
        { id: 8, name: "MATEMATICA APLICADA II" },
        { id: 9, name: "INGLES II" },
        { id: 10, name: "BASE DE DATOS II" },
        { id: 11, name: "INGENIERIA DE SOFTWARE" },
        { id: 12, name: "TALLER DE INTEGRACION II" },
        { id: 13, name: "ORIENTACION Y VALORES" },
        { id: 14, name: "MINERIA DE DATOS" },
      ],
    },
  ],
};

//Array de localidades, Formosa Argentina
export const DataLocalidades = [
  { name: "Formosa Capital" },
  { name: "El Colorado" },
  { name: "Clorinda" },
  { name: "Laguna Blanca" },
  { name: "General Belgrano" },
];

//Array de barrios, respectivos para c/ localidad
export const DataBarrios = {
  "Formosa Capital": [
    { name: "12 DE OCTUBRE", houses: 526 },
    { name: "2 DE ABRIL", houses: 1022 },
    { name: "BARRIO MILITAR", houses: 119 },
    { name: "OBRERO", houses: 1401 },
    { name: "BARRIO VIAL", houses: 958 },
    { name: "DON BOSCO", houses: 1606 },
    { name: "EL MISTOL", houses: 98 },
    { name: "EL RESGUARDO", houses: 513 },
    { name: "MANUEL BELGRANO", houses: 71 },
    { name: "EMILIO TOMAS", houses: 340 },
    { name: "EVA PERÓN", houses: 2200 },
    { name: "GUADALUPE", houses: 1435 },
    { name: "INDEPENDENCIA", houses: 1462 },
    { name: "J.F. KENNEDY", houses: 90 },
    { name: "JUAN D. PERÓN", houses: 1143 },
    { name: "LA FLORESTA", houses: 831 },
    { name: "LAS DELICIAS", houses: 213 },
    { name: "LIBORSI", houses: 714 },
    { name: "MARIANO MORENO", houses: 1636 },
    { name: "NANQOM", houses: 433 },
    { name: "SAN AGUSTÍN", houses: 780 },
    { name: "SAN FRANCISCO", houses: 2222 },
    { name: "SAN JOSÉ OBRERO", houses: 741 },
    { name: "SAN MARTÍN", houses: 3814 },
    { name: "SAN MIGUEL", houses: 1333 },
    { name: "SAN PEDRO", houses: 743 },
    { name: "SANTA ROSA", houses: 421 },
    { name: "SIMÓN BOLIVAR", houses: 2161 },
    { name: "VENEZUELA", houses: 619 },
    { name: "VILLA DEL ROSARIO", houses: 1106 },
    { name: "VILLA HERMOSA", houses: 505 },
    { name: "VILLA LA PILAR", houses: 954 },
    { name: "VILLA LOURDES", houses: 1244 },
    { name: "VIRGEN DE LUJÁN", houses: 316 },
    { name: "LA ESPERANZA", houses: 180 },
    { name: "7 DE MAYO", houses: 368 },
    { name: "ANTENOR GAUNA", houses: 1069 },
    { name: "1° DE MAYO", houses: 184 },
    { name: "EL PORVENIR", houses: 352 },
    { name: "BERNARDINO RIVADAVIA", houses: 890 },
    { name: "VIRGEN DE ITATÍ", houses: 782 },
    { name: "PARQUE INDUSTRIAL", houses: 27 },
    { name: "SAN JUAN BAUTISTA", houses: 671 },
    { name: "16 DE JULIO", houses: 73 },
    { name: "SAG. CORAZÓN DE MARÍA", houses: 100 },
    { name: "ARTURO ILLIA", houses: 935 },
    { name: "HIPÓLITO IRIGOYEN", houses: 193 },
    { name: "SAN CAYETANO", houses: 217 },
    { name: "FACUNDO QUIROGA", houses: 82 },
    { name: "SAN ANDRES", houses: 177 },
    { name: "SANTA LUCÍA", houses: 101 },
    { name: "LA VIRGEN NIÑA", houses: 184 },
    { name: "17 DE OCTUBRE", houses: 123 },
    { name: "LIBERTAD", houses: 129 },
    { name: "ISLAS MALVINAS", houses: 197 },
    { name: "COLLUCCIO", houses: 443 },
    { name: "SAN ISIDRO LABRADOR", houses: 396 },
    { name: "ROBERTO SOTELO", houses: 133 },
    { name: "8 DE MARZO", houses: 226 },
    { name: "CO.VI.FOL.", houses: 124 },
    { name: "FONTANA", houses: 1232 },
    { name: "SOLANO LIMA", houses: 217 },
    { name: "LA ESTRELLA", houses: 53 },
    { name: "20 de JULIO", houses: 225 },
    { name: "REPÚBLICA ARGENTINA", houses: 1895 },
    { name: "8 DE OCTUBRE", houses: 344 },
    { name: "EL QUEBRANTO", houses: 152 },
    { name: "EL QUEBRACHITO", houses: 450 },
    { name: "EL PALOMAR", houses: 493 },
    { name: "STELLA MARIS", houses: 216 },
    { name: "LOS INMIGRANTES", houses: 112 },
    { name: "LAS ORQUIDEAS", houses: 275 },
    { name: "Dr. RICARDO BALBÍN", houses: 170 },
    { name: "SAN JUAN", houses: 316 },
    { name: "SAN ANTONIO", houses: 454 },
    { name: "PARQUE URBANO", houses: 522 },
    { name: "ARTURO ILLIA II", houses: 670 },
    { name: "YAPEYÚ", houses: 536 },
    { name: "8 DE OCTUBRE BIS", houses: 234 },
    { name: "CARACOLITO", houses: 278 },
    { name: "CONO SUR", houses: 182 },
    { name: "EL PALMAR", houses: 268 },
    { name: "EL PUCÚ", houses: 321 },
    { name: "EL TIMBÓ I", houses: 156 },
    { name: "EL TIMBÓ II", houses: 299 },
    { name: "EVITA", houses: 205 },
    { name: "FEDERACIÓN", houses: 221 },
    { name: "FLEMING", houses: 169 },
    { name: "GUAYAIBÍ", houses: 304 },
    { name: "ITATÍ I", houses: 150 },
    { name: "ITATÍ II", houses: 277 },
    { name: "JUAN MANUEL DE ROSAS", houses: 189 },
    { name: "LA PAZ", houses: 253 },
    { name: "MALVINAS", houses: 212 },
    { name: "NUEVA FORMOSA", houses: 184 },
    { name: "NUEVA POMPEYA", houses: 322 },
    { name: "PARQUE URBANO I", houses: 305 },
    { name: "PARQUE URBANO II", houses: 185 },
    { name: "SAN PÍO X", houses: 257 },
    { name: "SAN JOSÉ OBRERO", houses: 311 },
    { name: "SARMIENTO", houses: 278 },
    { name: "URUNDAY", houses: 226 },
    { name: "VILLA JARDÍN", houses: 300 },
    { name: "VIRGEN DEL CARMEN", houses: 245 },
    { name: "VIRGEN NUESTRA SEÑORA DEL PILAR", houses: 178 },
    { name: "LOTE 4", houses: 158 },
    { name: "LUJAN", houses: 274 },
    { name: "ZONA RURAL", houses: 783 },
  ],
  Colorado: [
    { name: "CENTRO", houses: 287 },
    { name: "OBRERO", houses: 384 },
    { name: "SAN MIGUEL", houses: 431 },
    { name: "SAN FRANCISCO", houses: 308 },
  ],
  "General Belgrano": [
    { name: "CENTRO", houses: 391 },
    { name: "40 VIVIENDAS", houses: 492 },
    { name: "12 DE OCTUBRE", houses: 359 },
  ],
  "Laguna Blanca": [
    { name: "CENTRO", houses: 406 },
    { name: "SAN JUAN", houses: 481 },
    { name: "SAN MIGUEL", houses: 532 },
    { name: "BELGRANO", houses: 357 },
  ],
  Clorinda: [
    { name: "CENTRO", houses: 512 },
    { name: "25 DE MAYO", houses: 401 },
    { name: "LIBERTAD", houses: 535 },
    { name: "PORTEÑO NORTE", houses: 296 },
    { name: "240 VIVIENDAS", houses: 452 },
  ],
};

//Array modalidades asignadas a partir del 4to año de secundaria
export const DataModalidadesSecundaria = [
  { name: "Cs. Sociales" },
  { name: "Cs. Naturales" },
  { name: "Economía y Comercio" },
  { name: "Producción de Bienes y Servicios" },
];

//======================================//
//======================================//
//======================================//
//======================================//
